name: cp-testing1
favicon: null
layout_spectrum: 0.15576
typography_spectrum: 0.37872
title: Chris Paltzat - Photojournal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96a9be'
    - '#dae5eb'
    - '#537ead'
    - '#283f4c'
    - '#8c896a'
  brandStrength: 0.625
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
