name: cp-testing1
favicon: null
layout_spectrum: 0.7477
typography_spectrum: 0.2962
title: Chris Paltzat - Photojournal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141817'
    - '#eeede9'
    - '#bdcdd5'
    - '#2f668c'
    - '#454032'
  brandStrength: 0.0625
  lightness: 0.4371882686391473
  saturation: 0.6300167280714959
  rhythmicContrast: 0.7708492854144424
purpose: []
