name: cp-testing1
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37047
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0d11'
    - '#3a5f9a'
    - '#f5f5f5'
    - '#6f93c9'
    - '#b5d8eb'
  brandStrength: 0.375
  lightness: 0.4371882686391473
  saturation: 0.6300167280714959
  rhythmicContrast: 0.7708492854144424
purpose: []
