name: cp-testing1
favicon: null
layout_spectrum: 0.5639
typography_spectrum: 0.2962
title: Chris Paltzat - Photojournal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4f73a0'
    - '#abb9cc'
    - '#000000'
    - '#f7eee7'
    - '#f80034'
  brandStrength: 0.625
  lightness: 0.4371882686391473
  saturation: 0.6300167280714959
  rhythmicContrast: 0.7708492854144424
purpose: []
