name: cp-testing1
favicon: null
layout_spectrum: 0.42574
typography_spectrum: 0.2962
title: Chris Paltzat - Photojournal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#337cfc'
    - '#2b3fd4'
    - '#2d1b27'
    - '#56303d'
    - '#8b536b'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
