name: cp-testing1
favicon: null
layout_spectrum: 0.57849
typography_spectrum: 0.2962
title: Chris Paltzat - Photojournal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#133461'
    - '#b6bdc8'
    - '#357bb6'
    - '#92a0ba'
    - '#070e0f'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
